### ISSUE TITLE
Update Cocoapods version to 1.3.0

### ISSUE THREAD

**Issue by j0rdsta** [LiveUI/Awesome#10]
Hey, thanks for getting version 1.3.0 out the door! I've been using some Pro icons in my UI designs and I'm excited to get this new version into my project.

Just one problem: in pull request #8, nobody ran the Cocoapods installation test before the merge. Because the Podspec didn't get updated (and whatever else is involved), I'm unable to install version 1.3.0 via `pod install` without it falling back to installing 1.2.0.

Can we get the Cocoapods install updated? And can we mandate that Cocoapod installs get tested before new versions get released?

I'd submit a PR for this myself but I'm pretty new to Cocoapods :|

**Comment by j0rdsta** [comment]
You can tell I'm a Cocoapods noob - I just got it working by adding this to my Podfile:

```ruby
pod 'AwesomeEnum', :git => 'https://github.com/LiveUI/Awesome.git', :tag => '1.3.0'
```

Heh, I guess updating the Podspec file isn't such a priority any more. Still would be good though!

**Comment by bdrelling** [comment]
I agree--there's the git workaround now that I know v1.3.0 is even a thing, but please update this in Cocoapods... I'm a new user of the repo and just noticed when `bookOpen` was unavailable. Checked the repo, saw it was, checked the releases, and found the version mismatch.

**Comment by dimagimburg** [comment]
Version should be now updated on pods. thanks @rafiki270
