### ISSUE TITLE
Pro not working for me

### ISSUE THREAD

**Issue by matt-matt1** [LiveUI/Awesome#14]
Inserted in AppDelegate:
_AwesomePro.loadFonts(from: Bundle.main)_ (as per instructions)
and copied the font (4 x ttf) files to a folder named Fonts. (Names unchanged eg. _fa-brands-400.ttf_) (By dragging from finder into project)
![assets-fonts](https://user-images.githubusercontent.com/13394463/44005477-1fbade0e-9e42-11e8-98cf-bbc801b1e750.png)
Then I used **AwesomePro.light...** in place were I had **Awesome.regular...**
It threw an error, so I copied the font files to the official assets folder - still get the same error!

I ensured the files were fine by opening them with Apple's font book - they looked fine.
Have I missed an important step?  Or done a step incorrectly?

**Comment by rafiki270** [comment]
Seems like you are moving them into an asset folder instead of the project itself

**Comment by matt-matt1** [comment]
It still says ..Did you forget to call AwesomePro.loadFonts(from:)?
I copied the files into the top of the project. (Tried as first files, last files - also tried in Pods > AwesomeEnum > Resources, - same error.)
And I checked agin that line is in _didFinishLaunchingWithOptions_.
Tried using the "AwesomePro.regular.addressBook", because I know that works in the free Awesome...  No matter what the same error appears.

**Comment by rafiki270** [comment]
do you have the fonts in your info.plist file? Slack me if you'd like a faster response 

http://bit.ly/2B0dEyt

**Comment by matt-matt1** [comment]
Can you show what to write in Info.plist?
Joined Slack, in LiveUI, ...

**Comment by rafiki270** [comment]
https://developer.apple.com/documentation/uikit/text_display_and_fonts/adding_a_custom_font_to_your_app
