### ISSUE TITLE
Unable to find spec for AwesomeEnum

### ISSUE THREAD

**Issue by zacpwhite** [LiveUI/Awesome#16]
I'm currently trying to install AwesomeEnum using CocoaPods and am receiving the error `Unable to find a specification for AwesomeEnum`.

**Comment by zacpwhite** [comment]
After following the recommendation in [this](https://github.com/LiveUI/Awesome/issues/10#issuecomment-404391006) comment, I was able to install, however version 1.3.0 should be pushed to the CocoaPods trunk, as version 1.2.0 is the only version currently visible there.

**Comment by padarom** [comment]
Not a CocoaPods user, but it seems to me that CocoaPods is on 1.3.0 now: https://cocoapods.org/pods/AwesomeEnum

**Comment by rafiki270** [comment]
Yeah, I updated it few days ago
