### ISSUE TITLE
Icon cabinet-filing not found

### ISSUE THREAD

**Issue by ghowen** [LiveUI/Awesome#20]
Hi, I was just checking out this library and saw that it also support the Pro icons. Great work, so thank you for this! By testing I saw that the cabinet-filing icon is missing though. Can that be added? Thanks!

**Comment by ghowen** [comment]
Ah, it's already on GitHub but not in the pod yet.

**Comment by ghowen** [comment]
I see the podspec updated, but cocoapods is still delivering 1.3.0. Thanks.

**Comment by padarom** [comment]
Pod 2.0.1 is now live :tada:
