### ISSUE TITLE
Thread 1: Fatal error: Font FontAwesome5Pro-Regular not loaded properly. Did you forget to call AwesomePro.loadFonts(from:)?

### ISSUE THREAD

**Issue by philosopherdog** [LiveUI/Awesome#41]
I'm installing using cocoapods. Using version 2.1.0. I am calling Thread 1: Fatal error: Font AwesomePro.loadFonts(from:) in the AppDelegate application(_: didFinishLaunchingWithOptions:).

**Comment by hslightnin** [comment]
Also getting this, tried renaming to the old format still no joy

**Comment by philosopherdog** [comment]
I found a related discussion here: https://github.com/dzenbot/Iconic/issues/35#issuecomment-241209203 . I got it working by removing the files from copied bundle resources and adding them back in. I'm not entirely sure but if you register the fonts twice this will cause a crash. Can anyone shed light on this bug. It's weird because everyone on my team was able to build and I cloned and removed derived data but still could not build without this crash. I thought it was a cocoapods issue and was chasing my tail there for a while before starting to look elsewhere.

**Comment by ServicePal** [comment]
For what it's worth, I installed our Font Awesome 5 Pro fonts yesterday, pulled 2.10 using Cocoa pods and it all works like a charm. Great job on this library.

I added the fonts and left them with default file names
<img width="281" alt="Screen Shot 2019-04-04 at 9 14 11 AM" src="https://user-images.githubusercontent.com/8471863/55571382-44d18b80-56ba-11e9-901b-c5dfdd998ee5.png">.

**Comment by rafiki270** [comment]
thank you @ServicePal ... I am sorry but will have to close this unless we get more to go on ... :(
