### ISSUE TITLE
Missing Icons

### ISSUE THREAD

**Issue by syky27** [LiveUI/Awesome#5]
I am unable to find these icons in the framework

https://fontawesome.com/icons/allergies?style=solid
https://fontawesome.com/icons/notes-medical?style=solid

**Comment by gabisanmartin12** [comment]
And these:

https://fontawesome.com/icons/file-medical?style=solid
https://fontawesome.com/icons/briefcase-medical?style=solid

**Comment by syky27** [comment]
https://fontawesome.com/icons/history?style=solid

**Comment by rafiki270** [comment]
should be all in now in #1.2.0
