### ISSUE TITLE
Font Awesome 5 Pro

### ISSUE THREAD

**Issue by ibeleliev** [LiveUI/Awesome#6]
I have a question.
If I buy the Pro license of Font Awesome, will I be able to use pro icons with your library ?
Like if i copy and paste the fonts inside the Assets folder or I must do something else.

**Comment by rafiki270** [comment]
I got the pro livense as well, just need to generate the enums for it. Will try to do it this weekend. Watch this place :)

**Comment by ghowen** [comment]
Following, as I would love (!) to see this too. Any update on the progress? Thanks!

**Comment by rafiki270** [comment]
@ghowen I'll try this week, sorry it's taking so long, the work is crazy :(

**Comment by padarom** [comment]
I'll gladly have a look and try to implement this if you're too busy.

What I like about this library currently is that autocomplete only suggests icons that you can access (i.e. free icons). When pro icons are also available, there's no way of knowing anymore which icons are free and which require a license. Does it make sense in that case to add an additional enum such as `Awesome.pro`, which works the same as `Awesome`, but with the additional icons (and `thin` type), or do we want to lose the knowledge about which icons are pro and which aren't?

**Comment by padarom** [comment]
Sure, I'd love to.

**Comment by rafiki270** [comment]
Released
