### ISSUE TITLE
Error while launching from cocoa pods

### ISSUE THREAD

**Issue by matt-matt1** [LiveUI/Awesome#7]
I tried installing via Cocoapods.  In my pod file, like your instructions, I added “pod ‘AwesomeEnum’”.  I keep getting the error - [!] Unable to find a specification for `AwesomeEnum`.

(I accicdently typed wrong first, and install ‘Awesome’ fine…)

Why the error?  I know it has many users, did something odd happen recently?  How can I try out this?

PS.  I’ve install other pods without problems, then removed them as not needed anymore.

**Comment by rafiki270** [comment]
Hi Matt, I am not sure but I am using the pod as I type this message and all is fine, my podfile is here:
https://github.com/LiveUI/Boost-iOS/blob/master/Podfile

**Comment by rafiki270** [comment]
can you share your podfile?

**Comment by matt-matt1** [comment]
platform :ios , '9.1'

project '/Volumes/SHARED/xcode/MyApp/MyApp.xcodeproj'
target 'MyApp' do
  use_frameworks!

#pod 'Siesta', '~> 1.0'
#pod 'Siesta/UI', '~> 1.0'
#pod 'Alamofire', '~>4.5'
#pod 'Former'
#pod 'SwiftForms'
#pod 'SwiftyFORM'
#pod 'Eureka'
#pod 'AngleGradientLayer', '~> 1.0'
#pod 'SwiftyJSON'
#pod "SwiftDataTables"
#pod 'PCLBlurEffectAlert'
pod 'MGSwipeTableCell'
#pod 'Awesome'
pod 'AwesomeEnum', '~> 1.2.0'

end


As you can see I've tried many pods in the past.  Now I have eliminated most, instead using a more pure approach.
Before this, I installed 'Awesome' by mistake, then I commented it out.  Just tried adding the version number (which I didn't have before) and it still fails.
Perhaps I'd be better to install thing manually, please provide the instructions for that.

**Comment by matt-matt1** [comment]
It worked in another project.  (Something is mixed-up between the project and cocoa pods.)
