### ISSUE TITLE
How To Have Awesome.Image as a parameter?

### ISSUE THREAD

**Issue by chitgoks** [LiveUI/Awesome#74]
it doesnt accept if i do this
```
func test(_ icon: Awesome.Image? = nil) {
}
```

I am trying to avoid using AnyView here. is it possible?

**Comment by rafiki270** [comment]
Can you just use Amazing? (Protocol)

**Comment by chitgoks** [comment]
still new. you mean like 

func(_ temp: Amazing) 

?
